-- MySQL Script generated by MySQL Workbench
-- Sat Sep 14 22:28:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `Biblioteca` ;

-- -----------------------------------------------------
-- Table `Biblioteca`.`Libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`Libros` (
  `idLibro` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(60) NOT NULL,
  `Edicion` INT NULL,
  `Año` INT NULL,
  `Idioma` VARCHAR(20) NULL,
  `Editorial` VARCHAR(45) NULL,
  `Localizacion` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `ISBN` VARCHAR(40) NULL,
  `Cantidad` INT NOT NULL,
  `Habilitado` TINYINT NULL,
  `Fecha_Ingreso` DATE NOT NULL,
  `UnidadesDisponibles` INT NOT NULL,
  PRIMARY KEY (`idLibro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`Categorias` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `Categoria` VARCHAR(45) NOT NULL,
  `idCategoriaPadre` INT NULL,
  `icono` VARCHAR(50) NULL,
  `Habilitado` TINYINT(1) NULL,
  PRIMARY KEY (`idCategoria`),
  INDEX `fk_Categorias_Categorias_idx` (`idCategoriaPadre` ASC) VISIBLE,
  UNIQUE INDEX `Categoria_UNIQUE` (`Categoria` ASC) VISIBLE,
  CONSTRAINT `fk_Categorias_Categorias`
    FOREIGN KEY (`idCategoriaPadre`)
    REFERENCES `Biblioteca`.`Categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`TipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`TipoUsuario` (
  `idTipoUsuario` INT NOT NULL AUTO_INCREMENT,
  `TipoUsuario` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idTipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`Usuarios` (
  `IDUsuario` INT NOT NULL AUTO_INCREMENT,
  `PrimerNombre` VARCHAR(20) NOT NULL,
  `SegundoNombre` VARCHAR(20) NULL,
  `PrimerApellido` VARCHAR(20) NOT NULL,
  `SegundoApellido` VARCHAR(20) NULL,
  `NumeroCuenta` INT NOT NULL,
  `NumeroTelefono` VARCHAR(15) NOT NULL,
  `CorreoInstitucional` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(255) NOT NULL,
  `FechaCreacion` DATE NOT NULL,
  `TipoUsuario` INT NOT NULL,
  `Habilitado` TINYINT(1) NOT NULL,
  `Reputacion` INT NOT NULL,
  PRIMARY KEY (`IDUsuario`),
  INDEX `fk_Usuarios_TipoUsuario1_idx` (`TipoUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_TipoUsuario1`
    FOREIGN KEY (`TipoUsuario`)
    REFERENCES `Biblioteca`.`TipoUsuario` (`idTipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`Reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`Reservas` (
  `idReserva` INT NOT NULL AUTO_INCREMENT,
  `UsuarioAReservar` INT NOT NULL,
  `FechaReserva` DATE NOT NULL,
  `Estado` VARCHAR(15) NOT NULL,
  `idLibro` INT NOT NULL,
  `Checkout` DATE NULL,
  PRIMARY KEY (`idReserva`),
  INDEX `fk_Reservas_Usuarios1_idx` (`UsuarioAReservar` ASC) VISIBLE,
  INDEX `fk_Reservas_Libros1_idx` (`idLibro` ASC) VISIBLE,
  CONSTRAINT `fk_Reservas_Usuarios1`
    FOREIGN KEY (`UsuarioAReservar`)
    REFERENCES `Biblioteca`.`Usuarios` (`NumeroCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservas_Libros1`
    FOREIGN KEY (`idLibro`)
    REFERENCES `Biblioteca`.`Libros` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`HistorialPrestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`HistorialPrestamos` (
  `idPrestamo` INT NOT NULL AUTO_INCREMENT,
  `FechaADevolver` DATETIME NOT NULL,
  `ObservacionInicial` VARCHAR(100) NULL,
  `Estado` VARCHAR(20) NOT NULL,
  `FechaDevolucion` DATE NULL,
  `ObservacionFinal` VARCHAR(100) NULL,
  `IDAdministradorPrestamo` INT NOT NULL,
  `idReserva` INT NOT NULL,
  `IDAdministradorRecepcion` INT NOT NULL,
  PRIMARY KEY (`idPrestamo`),
  INDEX `fk_HistorialPrestamos_Usuarios3_idx` (`IDAdministradorPrestamo` ASC) VISIBLE,
  INDEX `fk_HistorialPrestamos_Reservas1_idx` (`idReserva` ASC) VISIBLE,
  INDEX `fk_HistorialPrestamos_Usuarios1_idx` (`IDAdministradorRecepcion` ASC) VISIBLE,
  CONSTRAINT `fk_HistorialPrestamos_Usuarios3`
    FOREIGN KEY (`IDAdministradorPrestamo`)
    REFERENCES `Biblioteca`.`Usuarios` (`IDUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HistorialPrestamos_Reservas1`
    FOREIGN KEY (`idReserva`)
    REFERENCES `Biblioteca`.`Reservas` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HistorialPrestamos_Usuarios1`
    FOREIGN KEY (`IDAdministradorRecepcion`)
    REFERENCES `Biblioteca`.`Usuarios` (`IDUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`HistorialCobros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`HistorialCobros` (
  `idCobro` INT NOT NULL AUTO_INCREMENT,
  `UsuarioACobrar` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Motivo` VARCHAR(100) NOT NULL,
  `idAdministradorACargo` INT NOT NULL,
  PRIMARY KEY (`idCobro`),
  INDEX `fk_HistorialCobros_Usuarios1_idx` (`UsuarioACobrar` ASC) VISIBLE,
  INDEX `fk_HistorialCobros_Usuarios2_idx` (`idAdministradorACargo` ASC) VISIBLE,
  CONSTRAINT `fk_HistorialCobros_Usuarios1`
    FOREIGN KEY (`UsuarioACobrar`)
    REFERENCES `Biblioteca`.`Usuarios` (`NumeroCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HistorialCobros_Usuarios2`
    FOREIGN KEY (`idAdministradorACargo`)
    REFERENCES `Biblioteca`.`Usuarios` (`IDUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`Autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`Autores` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(90) NOT NULL,
  `Apellidos` VARCHAR(90) NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`LibrosAutores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`LibrosAutores` (
  `idLibro` INT NOT NULL,
  `idAutor` INT NOT NULL,
  PRIMARY KEY (`idLibro`, `idAutor`),
  INDEX `fk_Libros_has_Autores_Autores1_idx` (`idAutor` ASC) VISIBLE,
  INDEX `fk_Libros_has_Autores_Libros1_idx` (`idLibro` ASC) VISIBLE,
  CONSTRAINT `fk_Libros_has_Autores_Libros1`
    FOREIGN KEY (`idLibro`)
    REFERENCES `Biblioteca`.`Libros` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libros_has_Autores_Autores1`
    FOREIGN KEY (`idAutor`)
    REFERENCES `Biblioteca`.`Autores` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`LibrosCategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`LibrosCategorias` (
  `idLibro` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`idLibro`, `idCategoria`),
  INDEX `fk_Libros_has_Categorias_Categorias1_idx` (`idCategoria` ASC) VISIBLE,
  INDEX `fk_Libros_has_Categorias_Libros1_idx` (`idLibro` ASC) VISIBLE,
  CONSTRAINT `fk_Libros_has_Categorias_Libros1`
    FOREIGN KEY (`idLibro`)
    REFERENCES `Biblioteca`.`Libros` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libros_has_Categorias_Categorias1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `Biblioteca`.`Categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Biblioteca` ;

-- -----------------------------------------------------
-- procedure obtener_libros_por_categoria
-- -----------------------------------------------------

DELIMITER $$
USE `Biblioteca`$$
CREATE PROCEDURE `obtener_libros_por_categoria` (IN id_categoria int)
BEGIN
	SELECT Libros.idLibro, Libros.Titulo,Libros.ISBN,Autores.Nombres FROM Libros 
    INNER JOIN LibrosCategorias ON LibrosCategorias.idLibro  =  Libros.idLibro 
    INNER JOIN LibrosAutores ON LibrosAutores.idLibro = Libros.idLibro
    INNER JOIN Autores ON Autores.idAutor = LibrosAutores.idLibro
    WHERE idCategoria = id_categoria ORDER BY Libros.Titulo ;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
